In [25]:
import numpy as np
import pandas as pd
from __future__ import (absolute_import, division, print_function, unicode_literals)
import os
from surprise import SVD
from surprise import Dataset
from surprise import Reader
from surprise.model_selection import cross_validate

## Data Load

In [26]:
file_path = os.path.expanduser('~/.surprise_data/ml-100k/ml-100k/u.data')
reader = Reader(line_format = 'user item rating timestamp', sep = '\t')
data = Dataset.load_from_file(file_path, reader = reader)

In [27]:
algo = SVD()
cross_validate(algo, data, measures = ['RMSE', 'MAE'], cv = 5, verbose = True)

Evaluating RMSE, MAE of algorithm SVD on 5 split(s).

                  Fold 1  Fold 2  Fold 3  Fold 4  Fold 5  Mean    Std     
RMSE (testset)    0.9347  0.9423  0.9330  0.9471  0.9310  0.9376  0.0061  
MAE (testset)     0.7380  0.7410  0.7351  0.7480  0.7324  0.7389  0.0054  
Fit time          12.40   13.51   12.61   11.04   13.83   12.68   0.98    
Test time         0.47    0.38    0.31    0.34    0.37    0.37    0.05    


{'test_rmse': array([0.9346969 , 0.9422943 , 0.932964  , 0.94709733, 0.93098753]),
 'test_mae': array([0.73804087, 0.74097557, 0.73513271, 0.74801885, 0.73238158]),
 'fit_time': (12.401796102523804,
  13.508845567703247,
  12.608235120773315,
  11.044529438018799,
  13.834606647491455),
 'test_time': (0.4650845527648926,
  0.37822699546813965,
  0.31382083892822266,
  0.3357243537902832,
  0.3719980716705322)}

In [28]:
df = pd.DataFrame(data.raw_ratings, columns = ['uid', 'iid', 'rate', 'timestamp'])

In [29]:
df

uid   iid  rate  timestamp
0      196   242   3.0  881250949
1      186   302   3.0  891717742
2       22   377   1.0  878887116
3      244    51   2.0  880606923
4      166   346   1.0  886397596
5      298   474   4.0  884182806
6      115   265   2.0  881171488
7      253   465   5.0  891628467
8      305   451   3.0  886324817
9        6    86   3.0  883603013
10      62   257   2.0  879372434
11     286  1014   5.0  879781125
12     200   222   5.0  876042340
13     210    40   3.0  891035994
14     224    29   3.0  888104457
15     303   785   3.0  879485318
16     122   387   5.0  879270459
17     194   274   2.0  879539794
18     291  1042   4.0  874834944
19     234  1184   2.0  892079237
20     119   392   4.0  886176814
21     167   486   4.0  892738452
22     299   144   4.0  877881320
23     291   118   2.0  874833878
24     308     1   4.0  887736532
25      95   546   2.0  879196566
26      38    95   5.0  892430094
27     102   768   2.0  883748450
28      63   277   4.0  875747401
29     160   234   5.0  876861185
...    ...   ...   ...        ...
99970  449   120   1.0  879959573
99971  661   762   2.0  876037121
99972  721   874   3.0  877137447
99973  821   151   4.0  874792889
99974  764   596   3.0  876243046
99975  537   443   3.0  886031752
99976  618   628   2.0  891308019
99977  487   291   3.0  883445079
99978  113   975   5.0  875936424
99979  943   391   2.0  888640291
99980  864   685   4.0  888891900
99981  750   323   3.0  879445877
99982  279    64   1.0  875308510
99983  646   750   3.0  888528902
99984  654   370   2.0  887863914
99985  617   582   4.0  883789294
99986  913   690   3.0  880824288
99987  660   229   2.0  891406212
99988  421   498   4.0  892241344
99989  495  1091   4.0  888637503
99990  806   421   4.0  882388897
99991  676   538   4.0  892685437
99992  721   262   3.0  877137285
99993  913   209   2.0  881367150
99994  378    78   3.0  880056976
99995  880   476   3.0  880175444
99996  716   204   5.0  879795543
99997  276  1090   1.0  874795795
99998   13   225   2.0  882399156
99999   12   203   3.0  879959583

[100000 rows x 4 columns]

In [30]:
user = list(set(df.uid))
item = list(set(df.iid))

## Basic CF algorithm

In [31]:
from surprise import KNNBasic
trainset = data.build_full_trainset()
sim_options = {'name' : 'cosine', 'user_based' : True}

In [32]:
algo = KNNBasic(k = 40, min_k = 1, simoptions = sim_options)
algo.fit(trainset)

Computing the msd similarity matrix...
Done computing similarity matrix.


In [33]:
pred_rating_basic = np.zeros((len(user) + 1, len(item) + 1))
for u in user:
    iids = df[df.uid == u]
    for i in range(1, len(iids) + 1):
        iid = iids[i - 1:i].iid.values[0]
        r_ui = iids[i - 1:i].rate.values[0]
        pred = algo.predict(u, iid, r_ui, verbose = False)
        pred_rating_basic[int(u)][int(iid)] = pred.est

In [34]:
pred_rating_basic # pred_rating_basic[uid][iid]

array([[0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 4.12997131, 3.1930005 , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 4.17483517, 0.        , ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.        , 4.49353944, 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 3.50017794, ..., 0.        , 0.        ,
        0.        ]])

## CF algorithm with mean

In [35]:
from surprise import KNNWithMeans

In [36]:
algo = KNNWithMeans(k = 40, min_k = 1, simoptions = sim_options)
algo.fit(trainset)

Computing the msd similarity matrix...
Done computing similarity matrix.


In [37]:
pred_rating_mean = np.zeros((len(user) + 1, len(item) + 1))
for u in user:
    iids = df[df.uid == u]
    for i in range(1, len(iids) + 1):
        iid = iids[i - 1:i].iid.values[0]
        r_ui = iids[i - 1:i].rate.values[0]
        pred = algo.predict(u, iid, r_ui, verbose = False)
        pred_rating_mean[int(u)][int(iid)] = pred.est

In [50]:
pred_rating_mean # pred_rating[uid][iid]

array([[0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 3.890355  , 3.17539145, ..., 0.        , 0.        ,
        0.        ],
       [0.        , 4.0140942 , 0.        , ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.        , 4.75242209, 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 3.30818473, ..., 0.        , 0.        ,
        0.        ]])

## CF algorithm with z-score

In [38]:
from surprise import KNNWithZScore

In [39]:
algo = KNNWithZScore(k = 40, min_k = 1, simoptions = sim_options)
algo.fit(trainset)

Computing the msd similarity matrix...
Done computing similarity matrix.


In [40]:
pred_rating_z = np.zeros((len(user) + 1, len(item) + 1))
for u in user:
    iids = df[df.uid == u]
    for i in range(1, len(iids) + 1):
        iid = iids[i - 1:i].iid.values[0]
        r_ui = iids[i - 1:i].rate.values[0]
        pred = algo.predict(u, iid, r_ui, verbose = False)
        pred_rating_z[int(u)][int(iid)] = pred.est

In [52]:
pred_rating_z # pred_rating[uid][iid]

array([[0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 3.96878304, 3.03329263, ..., 0.        , 0.        ,
        0.        ],
       [0.        , 4.04859899, 0.        , ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.        , 4.68476278, 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 3.20540185, ..., 0.        , 0.        ,
        0.        ]])

## SVD

In [41]:
from surprise import SVD

In [42]:
algo = SVD(n_factors = 100, n_epochs = 20, biased = False, lr_all = 0.005, reg_all = 0)
algo.fit(trainset)

In [43]:
pred_rating_svd = np.zeros((len(user) + 1, len(item) + 1))
for u in user:
    iids = df[df.uid == u]
    for i in range(1, len(iids) + 1):
        iid = iids[i - 1:i].iid.values[0]
        r_ui = iids[i - 1:i].rate.values[0]
        pred = algo.predict(u, iid, r_ui, verbose = False)
        pred_rating_svd[int(u)][int(iid)] = pred.est

In [53]:
pred_rating_svd # pred_rating[uid][iid]

array([[0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 5.        , 3.17588084, ..., 0.        , 0.        ,
        0.        ],
       [0.        , 3.76016444, 0.        , ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.        , 4.61737491, 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 3.76791589, ..., 0.        , 0.        ,
        0.        ]])

## PMF

In [44]:
from surprise import SVD

In [45]:
algo = SVD(n_factors = 100, n_epochs = 20, biased = False, lr_all = 0.005, reg_all = 0.02)
algo.fit(trainset)

In [46]:
pred_rating_pmf = np.zeros((len(user) + 1, len(item) + 1))
for u in user:
    iids = df[df.uid == u]
    for i in range(1, len(iids) + 1):
        iid = iids[i - 1:i].iid.values[0]
        r_ui = iids[i - 1:i].rate.values[0]
        pred = algo.predict(u, iid, r_ui, verbose = False)
        pred_rating_pmf[int(u)][int(iid)] = pred.est

In [54]:
pred_rating_pmf # pred_rating[uid][iid]

array([[0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 4.11393133, 3.07647591, ..., 0.        , 0.        ,
        0.        ],
       [0.        , 3.84283827, 0.        , ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.        , 4.30428769, 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 3.30187663, ..., 0.        , 0.        ,
        0.        ]])

## PMF with biased

In [47]:
from surprise import SVD

In [48]:
algo = SVD(n_factors = 100, n_epochs = 20, biased = True, lr_all = 0.005, reg_all = 0.02)
algo.fit(trainset)

In [49]:
pred_rating_pmf_bi = np.zeros((len(user) + 1, len(item) + 1))
for u in user:
    iids = df[df.uid == u]
    for i in range(1, len(iids) + 1):
        iid = iids[i - 1:i].iid.values[0]
        r_ui = iids[i - 1:i].rate.values[0]
        pred = algo.predict(u, iid, r_ui, verbose = False)
        pred_rating_pmf_bi[int(u)][int(iid)] = pred.est

In [55]:
pred_rating_pmf_bi # pred_rating[uid][iid]

array([[0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 3.9945954 , 3.38047108, ..., 0.        , 0.        ,
        0.        ],
       [0.        , 4.14281664, 0.        , ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.        , 4.40220499, 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 3.82112415, ..., 0.        , 0.        ,
        0.        ]])