# 6조 (17011709 정선아, 17011741 문성용, 17011742 김소영)

In [173]:
import warnings
warnings.filterwarnings("ignore")

import numpy as np
import pandas as pd

In [174]:
MovieLens_df = pd.read_table("ratings.dat", sep='::', header=None, names=['UserID','MovieID','Rating','Timestamp'])
MovieLens_df.drop(['Timestamp'], axis=1, inplace=True)
MovieLens_pivot = MovieLens_df.pivot_table(index='UserID', columns='MovieID', values='Rating')
row_index = MovieLens_pivot.isnull().sum(axis = 1).sort_values() # NaN이 적은 순으로 행 뽑아내기
MovieLens_pivot = pd.DataFrame(MovieLens_pivot, index=row_index.index)
# rating이 많은 사용자 1,000명
MovieLens_pivot = MovieLens_pivot.iloc[:1000,:]
col_index = MovieLens_pivot.isnull().sum(axis = 0).sort_values() # NaN이 적은 순으로 열 뽑아내기
MovieLens_pivot = pd.DataFrame(MovieLens_pivot, columns=col_index.index)
# rating이 많은 영화 1,000개
MovieLens_pivot = MovieLens_pivot.iloc[:,:1000]
# user_index = MovieLens_pivot.index.values # User ID 순서 기억하기
# user_index = pd.Series(user_index) # Index rename Simi인자로 넣기 위해 형태 변경
MovieLens_pivot.fillna(0, inplace=True)
MovieLens_pivot = MovieLens_pivot.astype('int64')
MovieLens_pivot = np.array(MovieLens_pivot) # 함수 인자로 넣기 위해 numpy array 형태로 변경

# 1. Cosine Similarity

In [202]:
def COS(data):
    num_users = np.size(data, axis=0)
    simCOS = np.zeros((num_users,num_users))  # 0으로 초기화 된 행렬 생성
    for u in range(0, num_users):  # 각 유저별로 for문 반복
        arridx_u = np.where(data[u, ] == 0)
        for v in range(u + 1, num_users):
            arridx_v = np.where(data[v, ] == 0)
            arridx = np.unique(np.concatenate((arridx_u, arridx_v), axis=None))

            U = np.delete(data[u, ], arridx)
            V = np.delete(data[v, ], arridx)

            if np.linalg.norm(U) == 0 or np.linalg.norm(V) == 0:
                simCOS[u, v] = 0
            else:
                simCOS[u, v] = np.dot(U, V) / (np.linalg.norm(U) * np.linalg.norm(V))

            simCOS[v, u] = simCOS[u, v]
    return simCOS

In [203]:
COS(A)

array([[0.        , 0.9165204 , 0.79442991, 0.63943019, 0.88069603],
       [0.9165204 , 0.        , 0.80671783, 0.82956136, 0.89472029],
       [0.79442991, 0.80671783, 0.        , 0.71842121, 0.84181887],
       [0.63943019, 0.82956136, 0.71842121, 0.        , 0.79530788],
       [0.88069603, 0.89472029, 0.84181887, 0.79530788, 0.        ]])

In [224]:
def PCC(data):
    num_users = np.size(data, axis=0)
    simPCC = np.zeros((num_users,num_users))  # 0으로 초기화 된 행렬 생성
    mean = np.nanmean(np.where(data != 0, data, np.nan), axis=1)
    for u in range(0, num_users):
        arridx_u = np.where(data[u, ] == 0)
        for v in range(u + 1, num_users):
            arridx_v = np.where(data[v, ] == 0)
            arridx = np.unique(np.concatenate((arridx_u, arridx_v), axis=None))

            U = np.delete(data[u, ], arridx) - mean[u]
            V = np.delete(data[v, ], arridx) - mean[v]

            if np.linalg.norm(U) == 0 or np.linalg.norm(V) == 0:
                simPCC[u, v] = 0
            else:
                simPCC[u, v] = np.dot(U, V) / (np.linalg.norm(U) * np.linalg.norm(V))

            simPCC[v, u] = simPCC[u, v]

    return simPCC

# 2. Pearson Correlation Coefficient

In [128]:
PCC(MovieLens_pivot)

array([[ 0.        ,  0.65707268,  0.26630576, ...,  0.02698069,
         0.11686485,  0.094992  ],
       [ 0.65707268,  0.        ,  0.25738696, ...,  0.02741278,
         0.15325623, -0.09991021],
       [ 0.26630576,  0.25738696,  0.        , ...,  0.13864556,
         0.16625119,  0.15649389],
       ...,
       [ 0.02698069,  0.02741278,  0.13864556, ...,  0.        ,
        -0.14768909,  0.29004726],
       [ 0.11686485,  0.15325623,  0.16625119, ..., -0.14768909,
         0.        , -0.35809302],
       [ 0.094992  , -0.09991021,  0.15649389, ...,  0.29004726,
        -0.35809302,  0.        ]])

# Rating

In [209]:
A = np.array([[4, 1, 1, 4, 2, 3, 5, 0, 4, 0],
              [0, 4, 2, 0, 3, 2, 5, 0, 4, 3],
              [2, 0, 4, 5, 2, 0, 1, 3, 4, 2],
              [1, 4, 0, 1, 4, 5, 0, 3, 1, 2],
              [1, 2, 3, 4, 0, 3, 4, 4, 2, 5]])
A

array([[4, 1, 1, 4, 2, 3, 5, 0, 4, 0],
       [0, 4, 2, 0, 3, 2, 5, 0, 4, 3],
       [2, 0, 4, 5, 2, 0, 1, 3, 4, 2],
       [1, 4, 0, 1, 4, 5, 0, 3, 1, 2],
       [1, 2, 3, 4, 0, 3, 4, 4, 2, 5]])

In [208]:
COS(A)

array([[0.        , 0.9165204 , 0.79442991, 0.63943019, 0.88069603],
       [0.9165204 , 0.        , 0.80671783, 0.82956136, 0.89472029],
       [0.79442991, 0.80671783, 0.        , 0.71842121, 0.84181887],
       [0.63943019, 0.82956136, 0.71842121, 0.        , 0.79530788],
       [0.88069603, 0.89472029, 0.84181887, 0.79530788, 0.        ]])

In [302]:
# 임시로 만들어 놓기
def basic_mean(mat, sim, k):
    predicted_rating = np.zeros(mat.shape)
    
    mean = np.nanmean(np.where(mat != 0, mat, np.nan), axis=1) # mean of user

    if(sim == 'COS'):
        Sim = COS(mat)
    elif(sim == 'PCC'):
        Sim = PCC(mat)
        
    k_neighbors = np.argsort(-Sim)
    k_neighbors = np.delete(k_neighbors, np.s_[k:], 1)

    NumUsers = np.size(mat, axis=0)
    
    for u in range(0, NumUsers):
        list_sim = Sim[u, k_neighbors[u]]
        list_rating = mat[k_neighbors[u]]
        list_mean = mean[k_neighbors[u]]
        
        mom = np.sum(list_sim)
        sun = np.sum(list_sim.reshape(-1,1) * (list_rating - list_mean.reshape(-1,1)), axis=0)
        predicted_rating[u] = mean[u] + sun / mom
        
    return predicted_rating

In [235]:
pd.DataFrame(A)

0  1  2  3  4  5  6  7  8  9
0  4  1  1  4  2  3  5  0  4  0
1  0  4  2  0  3  2  5  0  4  3
2  2  0  4  5  2  0  1  3  4  2
3  1  4  0  1  4  5  0  3  1  2
4  1  2  3  4  0  3  4  4  2  5

In [243]:
pd.DataFrame(basic_mean(A, 'COS', 3))

0         1         2         3         4         5         6  \
0  0.852409  1.993736  2.852409  2.791476  1.573520  1.626269  3.333557   
1  2.407053  2.647072  1.729349  3.423472  2.316521  3.994133  3.456401   
2  1.387715  2.077614  1.761762  2.421481  1.383407  2.412143  4.397775   
3  0.477036  1.619323  2.477036  2.414989  1.199685  1.250690  2.958721   
4  2.042926  1.757570  2.360433  3.007859  2.395500  1.746853  3.767066   

          7         8         9  
0  2.178407  3.219876  3.272625  
1  2.663491  2.745859  2.688165  
2  1.120719  3.053186  2.455969  
3  1.801816  2.845669  2.896674  
4  1.018576  4.053643  1.722503

In [247]:
tmp = pd.DataFrame(MovieLens_pivot)
tmp.head()

0    1    2    3    4    5    6    7    8    9    ...  990  991  992  993  \
0    5    5    4    4    5    4    4    5    5    5  ...    2    4    2    3   
1    5    2    3    4    3    3    5    5    5    5  ...    4    3    4    5   
2    5    5    5    4    4    5    5    5    5    5  ...    5    3    4    4   
3    5    5    5    5    5    3    3    5    1    4  ...    3    1    0    4   
4    4    4    3    4    3    5    5    2    3    3  ...    2    2    3    2   

   994  995  996  997  998  999  
0    3    3    3    0    0    4  
1    2    4    3    1    0    5  
2    0    0    3    4    0    5  
3    0    2    4    3    3    0  
4    0    0    0    2    0    3  

[5 rows x 1000 columns]

In [246]:
pd.DataFrame(basic_mean(MovieLens_pivot, 'COS', 10))

0         1         2         3         4         5         6    \
0    3.087396  3.786176  2.387602  1.487075  2.385845  1.787562  1.087888   
1    2.187077  2.786341  1.986564  2.385816  1.986982  1.384910  1.086462   
2    4.823643  4.424384  4.123968  3.222763  3.723005  3.924064  3.222502   
3    3.362624  3.061314  3.262264  1.463868  2.162297  1.964213  1.363241   
4    1.924100  3.225046  1.323420  1.324805  1.324540  1.925261  0.824861   
5    2.795212  2.195189  2.294617  1.195728  1.894776  0.896186  1.895391   
6    3.623221  3.122418  3.223495  2.922103  3.022329  2.522371  2.722387   
7    3.314362  3.513850  2.914775  2.415628  3.214722  3.513850  2.815917   
8    0.770112  2.169865  0.870651 -0.324715  1.169307  0.769145  0.571348   
9    2.523047  3.322284  2.822359  1.920694  1.623494  0.824525  1.521331   
10   2.535500  3.535237  2.535437  0.237393  1.239399  0.835699  0.738664   
11   1.835348  3.433713  2.434233  1.736235  1.636076  0.633977  1.535362   
12   2.785695  3.085942  2.786329  1.283002  2.282748  1.086641  1.382873   
13   4.580912  4.680872  3.380663  3.481341  3.781192  3.679345  3.281722   
14   1.019317  1.819036  1.218756 -0.179697 -0.180514  0.318587  0.219657   
15   1.110744  2.609826  1.910932  1.211588  0.911094  1.011065  0.410234   
16   3.453037  3.953713  2.754532  2.154836  2.353990  2.452223  1.754028   
17   2.291819  2.192169  2.688886  1.984862  0.887737  1.991164  1.086361   
18   3.275887  3.476120  3.676064  2.274924  2.375014  3.375715  1.774956   
19   3.144226  3.544826  2.845314  2.044438  1.946144  2.243886  1.645632   
20   2.080791  2.482521  2.380048  1.882473  1.681176  0.582726  1.281818   
21   2.395163  2.597458  0.898551  0.898864  0.099155  1.196142  0.995934   
22   2.676285  3.575945  1.778019  1.573528  1.776011  1.476042  1.474726   
23   1.556960  2.656521  1.159659  0.161067  0.060609  0.857523  0.958819   
24   3.873119  3.174735  2.874099  2.974525  3.572992  3.773506  3.572742   
25   2.795903  3.395827  3.094847  2.494760  2.097272  2.194500  2.196431   
26   3.772451  3.572909  3.173079  1.274142  2.473563  2.472567  1.673231   
27   3.529429  3.129800  3.129787  1.430348  2.530031  1.829799  1.630221   
28   4.429815  4.730108  3.130998  2.630461  2.530916  3.529827  2.731385   
29   2.178352  2.479374  1.679752  1.278678  1.779636  0.778851  1.577564   
..        ...       ...       ...       ...       ...       ...       ...   
970  2.244186  3.043944  1.346521  1.041757  0.445511  2.142031  0.844203   
971  3.622658  3.422402  2.522422  3.321517  2.422797  2.222271  2.323340   
972  3.853451  2.752992  3.253417  3.252807  2.353026  2.952745  2.352849   
973  3.451140  4.050806  2.651487  3.752335  3.750867  4.552935  3.852313   
974  3.887536  4.287273  2.687976  2.787396  2.988081  3.987170  1.986705   
975  3.032695  3.432690  3.334351  2.734038  2.632777  3.132769  2.132595   
976  3.702322  4.301895  3.902500  3.501195  3.102222  4.203021  2.802279   
977  3.810090  3.709840  4.310175  1.908136  2.907053  2.210022  1.508456   
978  2.894586  2.894666  2.198938  0.094022  1.589257  2.793811  1.189690   
979  4.459274  5.359099  3.858295  4.459132  3.859368  3.757750  3.658206   
980  3.058313  3.958332  3.552240  2.855558  3.158965  3.858344  3.557881   
981  4.224777  4.424474  4.324781  3.324894  3.524945  4.224722  2.424575   
982  4.168723  4.168723  4.368092  2.868304  3.668594  3.368708  2.968604   
983  2.254632  2.354000  2.453271  0.252487  0.754866  0.554889  0.551914   
984  3.966970  3.663693  2.856335  2.663020  2.764840  2.072654  2.963989   
985  2.848453  3.851422  2.750443  3.251639  3.651060  2.850338  2.448977   
986  2.218543  2.019772  1.715755  0.616072  0.715105  1.415164  2.417414   
987  4.661412  4.361884  3.160665  3.562367  3.262389  4.360932  3.861721   
988  4.607116  4.206512  3.806506  1.707095  2.807139  2.006308  2.707518   
989  4.409728  3.910246  4.009642  3.111121  4.409728  3.708849  3.610664   
990  4

In [248]:
pd.DataFrame(basic_mean(MovieLens_pivot.T, 'COS', 10))

0         1         2         3         4         5         6    \
0    3.339336  3.135496  4.635508  2.641939  3.136678  1.937022  2.338958   
1    3.523317  3.223526  4.321664  2.924619  3.620137  2.520902  2.023438   
2    3.898945  2.597887  4.697854  3.797163  2.797054  2.895825  2.997439   
3    3.612872  3.112963  3.912647  3.612255  2.412450  1.812786  3.012809   
4    3.583691  2.284768  4.480335  3.284879  2.981663  2.579810  2.782510   
5    3.496959  2.400169  4.697890  3.197939  3.197654  1.896424  2.498007   
6    3.734086  2.637492  4.834128  4.234624  3.136602  2.833323  2.733968   
7    3.943451  3.543054  4.443315  4.143806  3.442457  1.741205  2.743366   
8    3.831788  3.033350  4.832614  2.231498  2.531942  2.630922  2.331431   
9    4.258346  3.160653  4.459412  2.557861  3.656791  3.358707  2.958246   
10   3.956897  3.056223  4.357895  3.756904  3.356934  2.258534  3.357499   
11   4.461962  3.659763  5.161003  4.660888  3.861609  2.963072  3.960837   
12   3.912671  2.613977  4.513352  1.913008  2.913497  2.712819  2.712494   
13   4.114111  2.814218  4.813363  3.913859  2.513625  3.112083  3.013895   
14   3.820175  2.918667  4.519852  3.518253  3.618946  2.219019  2.920592   
15   4.364335  3.163120  4.764746  3.365069  2.464638  2.166089  2.864528   
16   2.245903  3.050390  3.549724  2.146992  3.048116  1.846311  1.147541   
17   4.585470  2.287255  4.885720  3.286236  2.685649  3.285193  3.286363   
18   4.129363  3.330366  4.929041  3.530254  3.928921  3.027729  3.228908   
19   4.936171  2.736654  4.936188  2.934418  3.335629  3.533943  3.635141   
20   4.052102  2.052309  4.151937  3.551583  3.151770  2.450773  3.151979   
21   4.387748  1.886165  4.887425  4.287246  2.888592  2.787980  2.987206   
22   3.635734  2.036545  4.435926  3.435191  3.436091  1.835328  2.536269   
23   3.661777  1.961333  4.260864  2.661752  2.959996  2.360508  2.061686   
24   1.194876  2.995127  3.499863  2.299234  2.797716  1.597879  0.696003   
25   4.833832  2.732923  3.434983  4.433509  4.033913  3.833539  2.534655   
26   4.500360  3.300042  5.000428  3.500164  3.399884  2.599962  3.299961   
27   3.307657  2.204821  3.807066  3.504206  2.406958  0.905338  2.105394   
28   3.817776  1.618640  3.817716  2.417340  2.618211  1.616579  1.718461   
29   4.226613  3.227892  4.826601  4.226945  3.226022  2.825583  3.226403   
..        ...       ...       ...       ...       ...       ...       ...   
970  2.578211  2.080871  3.879472  0.681746  2.181330  1.780578  2.179804   
971  3.536503  2.235985  4.636118  1.636320  2.836521  1.936049  1.736743   
972  3.108962  1.005681  3.808124  3.108963  2.508228  1.108577  2.202778   
973  4.738226  1.336758  4.339251  4.038068  3.438823  3.139322  2.337841   
974  3.175603  2.776311  4.074355  1.076736  2.373502  1.873981  1.074637   
975  2.503239  1.103291  2.407188  0.401582  1.702413  1.304100  1.103093   
976  2.671875  2.067507  2.876949  1.865901  0.771406  1.066929  0.475766   
977  2.197274  0.201330  3.397516  1.397980  2.302126  0.298962  0.897315   
978  3.492411  1.792047  3.692164  2.191054  1.693054  1.591544  1.991519   
979  3.591920  0.891840  3.492424  0.588529  2.690631  1.895114  1.492405   
980  2.809279  2.203131  2.709487  2.007898  2.108633  0.306683  1.607452   
981  3.373543  2.873283  4.373500  1.673304  3.173224  2.573461  3.073621   
982  2.275821  1.077666  2.678959  2.177556  1.078389  1.076107  0.578793   
983  3.816353  2.517183  4.116968  2.517759  2.717238  1.817829  2.417411   
984  3.718329  2.619454  4.218232  2.417276  2.018673  2.218632  2.019384   
985  2.537469  1.736793  2.939558 -1.062967  1.037222  1.440675  0.740248   
986  1.915545  1.816139  2.815945  2.514508  1.315169  0.217674  0.912999   
987  4.525851  2.327229  4.326023  1.624404  3.225937  3.224696  2.724265   
988  4.049618  1.948758  3.651589  0.946357  3.248501  2.350945  2.546850   
989  2.709867  1.606682  1.910229  2.007043  2.010320  1.209195  1.111558   
990  2

In [249]:
pd.DataFrame(basic_baseline(MovieLens_pivot.T, 'COS', 10))

[[  1  11   4 ... 833 834   0]
 [  0  11   4 ... 517 833   1]
 [ 11 399   1 ... 965 985   2]
 ...
 [591 932 616 ... 833 867 997]
 [249 399 973 ... 834 517 998]
 [971 931 541 ... 761 985 999]]
[[  1  11   4 ... 399 946 936]
 [  0  11   4 ... 932 936 946]
 [ 11 399   1 ...  14  24 199]
 ...
 [591 932 616 ... 876 959 573]
 [249 399 973 ... 567 435 823]
 [971 931 541 ... 823 987 690]]


0         1         2         3         4         5         6    \
0    3.339336  3.135496  4.635508  2.641939  3.136678  1.937022  2.338958   
1    3.523317  3.223526  4.321664  2.924619  3.620137  2.520902  2.023438   
2    3.898945  2.597887  4.697854  3.797163  2.797054  2.895825  2.997439   
3    3.612872  3.112963  3.912647  3.612255  2.412450  1.812786  3.012809   
4    3.583691  2.284768  4.480335  3.284879  2.981663  2.579810  2.782510   
5    3.496959  2.400169  4.697890  3.197939  3.197654  1.896424  2.498007   
6    3.734086  2.637492  4.834128  4.234624  3.136602  2.833323  2.733968   
7    3.943451  3.543054  4.443315  4.143806  3.442457  1.741205  2.743366   
8    3.831788  3.033350  4.832614  2.231498  2.531942  2.630922  2.331431   
9    4.258346  3.160653  4.459412  2.557861  3.656791  3.358707  2.958246   
10   3.956897  3.056223  4.357895  3.756904  3.356934  2.258534  3.357499   
11   4.461962  3.659763  5.161003  4.660888  3.861609  2.963072  3.960837   
12   3.912671  2.613977  4.513352  1.913008  2.913497  2.712819  2.712494   
13   4.114111  2.814218  4.813363  3.913859  2.513625  3.112083  3.013895   
14   3.820175  2.918667  4.519852  3.518253  3.618946  2.219019  2.920592   
15   4.364335  3.163120  4.764746  3.365069  2.464638  2.166089  2.864528   
16   2.245903  3.050390  3.549724  2.146992  3.048116  1.846311  1.147541   
17   4.585470  2.287255  4.885720  3.286236  2.685649  3.285193  3.286363   
18   4.129363  3.330366  4.929041  3.530254  3.928921  3.027729  3.228908   
19   4.936171  2.736654  4.936188  2.934418  3.335629  3.533943  3.635141   
20   4.052102  2.052309  4.151937  3.551583  3.151770  2.450773  3.151979   
21   4.387748  1.886165  4.887425  4.287246  2.888592  2.787980  2.987206   
22   3.635734  2.036545  4.435926  3.435191  3.436091  1.835328  2.536269   
23   3.661777  1.961333  4.260864  2.661752  2.959996  2.360508  2.061686   
24   1.194876  2.995127  3.499863  2.299234  2.797716  1.597879  0.696003   
25   4.833832  2.732923  3.434983  4.433509  4.033913  3.833539  2.534655   
26   4.500360  3.300042  5.000428  3.500164  3.399884  2.599962  3.299961   
27   3.307657  2.204821  3.807066  3.504206  2.406958  0.905338  2.105394   
28   3.817776  1.618640  3.817716  2.417340  2.618211  1.616579  1.718461   
29   4.226613  3.227892  4.826601  4.226945  3.226022  2.825583  3.226403   
..        ...       ...       ...       ...       ...       ...       ...   
970  2.578211  2.080871  3.879472  0.681746  2.181330  1.780578  2.179804   
971  3.536503  2.235985  4.636118  1.636320  2.836521  1.936049  1.736743   
972  3.108962  1.005681  3.808124  3.108963  2.508228  1.108577  2.202778   
973  4.738226  1.336758  4.339251  4.038068  3.438823  3.139322  2.337841   
974  3.175603  2.776311  4.074355  1.076736  2.373502  1.873981  1.074637   
975  2.503239  1.103291  2.407188  0.401582  1.702413  1.304100  1.103093   
976  2.671875  2.067507  2.876949  1.865901  0.771406  1.066929  0.475766   
977  2.197274  0.201330  3.397516  1.397980  2.302126  0.298962  0.897315   
978  3.492411  1.792047  3.692164  2.191054  1.693054  1.591544  1.991519   
979  3.591920  0.891840  3.492424  0.588529  2.690631  1.895114  1.492405   
980  2.809279  2.203131  2.709487  2.007898  2.108633  0.306683  1.607452   
981  3.373543  2.873283  4.373500  1.673304  3.173224  2.573461  3.073621   
982  2.275821  1.077666  2.678959  2.177556  1.078389  1.076107  0.578793   
983  3.816353  2.517183  4.116968  2.517759  2.717238  1.817829  2.417411   
984  3.718329  2.619454  4.218232  2.417276  2.018673  2.218632  2.019384   
985  2.537469  1.736793  2.939558 -1.062967  1.037222  1.440675  0.740248   
986  1.915545  1.816139  2.815945  2.514508  1.315169  0.217674  0.912999   
987  4.525851  2.327229  4.326023  1.624404  3.225937  3.224696  2.724265   
988  4.049618  1.948758  3.651589  0.946357  3.248501  2.350945  2.546850   
989  2.709867  1.606682  1.910229  2.007043  2.010320  1.209195  1.111558   
990  2

In [227]:
basic_mean(A.T, 'COS', 2)

array([[ 0.87554259,  0.87554259,  2.3463208 ,  0.817099  ,  1.817099  ],
       [ 0.76053179,  1.28073765,  2.19991423,  3.24032594,  1.63929666],
       [ 1.05819485, -0.91557369,  3.07131058,  1.09754204,  3.08442631],
       [ 3.27377025,  3.76426215,  4.74524595,  1.25475405,  3.23573785],
       [ 1.74774972,  2.75375047, -0.24924991,  4.24924991,  2.24924991],
       [ 3.50363719,  4.00181859,  1.49636281,  1.99090703,  2.00545578],
       [ 2.15749846,  3.11022797,  1.59841035,  4.15749846,  4.59841035],
       [ 1.08516188,  3.08272382,  3.58638092,  1.58150478,  4.58150478],
       [ 4.24020355,  0.24020355,  3.75979645,  1.24020355,  2.75979645],
       [ 0.95185309,  1.44934461,  2.45937853,  3.45436157,  1.96690398]])

In [228]:
basic_baseline(A.T, 'COS', 2)

[[8 7 6 3 9 5 4 2 1 0]
 [4 7 5 6 2 9 8 3 0 1]
 [7 3 5 1 9 8 4 6 0 2]
 [8 2 7 0 9 6 5 4 1 3]
 [1 5 7 9 6 2 8 0 3 4]
 [6 4 7 2 1 9 3 8 0 5]
 [5 9 7 4 1 8 0 3 2 6]
 [2 9 4 5 6 0 3 1 8 7]
 [3 0 6 2 7 9 4 1 5 8]
 [7 4 6 2 3 5 8 1 0 9]]
[[8 7]
 [4 7]
 [7 3]
 [8 2]
 [1 5]
 [6 4]
 [5 9]
 [2 9]
 [3 0]
 [7 4]]


array([[ 0.87554259,  0.87554259,  2.3463208 ,  0.817099  ,  1.817099  ],
       [ 0.76053179,  1.28073765,  2.19991423,  3.24032594,  1.63929666],
       [ 1.05819485, -0.91557369,  3.07131058,  1.09754204,  3.08442631],
       [ 3.27377025,  3.76426215,  4.74524595,  1.25475405,  3.23573785],
       [ 1.74774972,  2.75375047, -0.24924991,  4.24924991,  2.24924991],
       [ 3.50363719,  4.00181859,  1.49636281,  1.99090703,  2.00545578],
       [ 2.15749846,  3.11022797,  1.59841035,  4.15749846,  4.59841035],
       [ 1.08516188,  3.08272382,  3.58638092,  1.58150478,  4.58150478],
       [ 4.24020355,  0.24020355,  3.75979645,  1.24020355,  2.75979645],
       [ 0.95185309,  1.44934461,  2.45937853,  3.45436157,  1.96690398]])

In [229]:
basic_mean(A.T, 'COS', 2)

array([[ 0.87554259,  0.87554259,  2.3463208 ,  0.817099  ,  1.817099  ],
       [ 0.76053179,  1.28073765,  2.19991423,  3.24032594,  1.63929666],
       [ 1.05819485, -0.91557369,  3.07131058,  1.09754204,  3.08442631],
       [ 3.27377025,  3.76426215,  4.74524595,  1.25475405,  3.23573785],
       [ 1.74774972,  2.75375047, -0.24924991,  4.24924991,  2.24924991],
       [ 3.50363719,  4.00181859,  1.49636281,  1.99090703,  2.00545578],
       [ 2.15749846,  3.11022797,  1.59841035,  4.15749846,  4.59841035],
       [ 1.08516188,  3.08272382,  3.58638092,  1.58150478,  4.58150478],
       [ 4.24020355,  0.24020355,  3.75979645,  1.24020355,  2.75979645],
       [ 0.95185309,  1.44934461,  2.45937853,  3.45436157,  1.96690398]])

In [290]:
COS(A.T)[1,4]

0.9697622757528539

In [303]:
def basic_baseline(data, sim, k):
    # initializing (1000, 1000) numpy array with zeros
    predicted_rating = np.zeros(data.shape)

    # calculating means
    mean = np.nanmean(np.where(data != 0, data, np.nan))  # the mean of all ratings
    mean_u = np.nanmean(np.where(data != 0, data, np.nan), axis=1)  # the mean of all users
    mean_i = np.nanmean(np.where(data != 0, data, np.nan), axis=0)  # the mean of all items

    # base user, item
    b_u = mean_u - mean
    b_i = mean_i - mean
    # b_ui = mean + b_u + b_i

    # selecting similarity fuction
    if sim == 'COS':
        sim = COS(data)
    elif sim == 'PCC':
        sim = PCC(data)
        
    # selecting top k users by sorting similarity array
    k_users = np.argsort(-sim)
    k_users = np.delete(k_users, np.s_[k:], 1)  # delete colomn under k

    # number of users with axis = 0 condition
    num_users = np.size(data, axis=0)
    num_items = np.size(data, axis=1)

    
    # calculating predicted ratings
    for u in range(0, num_users):
        list_sim = sim[u, k_users[u]]  # selecting top k similarity
        for i in range(0, num_items):
            list_rating = data[k_users[u], i].astype('float64')  # k users' ratings on item i

            b_ui = mean + b_u[u] + b_i[i]  # scalar
            b_vi = mean + b_u[k_users[u]] + b_i[i]  # list

            # explanation of varialbles
            # mean_u[u] : user u의 평균
            # mean_i[i] : item i의 평균
            # b_u[u] : user u의 baseline
            # b_i[i] : item i의 baseline

            # calculation
            mom = np.sum(list_sim)  # 분모
            son = np.sum(list_sim * (list_rating - b_vi))  # 분자
            predicted_rating[u, i] = b_ui + son / mom

    return predicted_rating

In [284]:
A[0,7]

0

In [304]:
basic_baseline(A, 'COS', 2)

array([[ 0.28988047,  2.81978035,  2.28988047,  1.75998059,  1.32974698,
         2.28988047,  4.30981372,  1.75998059,  2.81978035,  3.77991384],
       [ 2.74888141,  1.72480939,  2.21879139,  4.2308274 ,  1.24286341,
         3.2308274 ,  4.7368454 ,  2.20675538,  3.24286341,  2.70073737],
       [ 0.18909227,  2.65715391,  2.18909227,  1.72103063,  1.14650779,
         2.18909227,  4.16780003,  1.72103063,  2.65715391,  3.69973839],
       [-0.08579346,  2.44582768,  1.91420654,  1.3825854 ,  0.95636806,
         1.91420654,  3.9352873 ,  1.3825854 ,  2.44582768,  3.40366616],
       [ 1.95132724,  2.47897423,  1.47107509,  1.95132724,  2.47107509,
         2.46317595,  4.96712552, -0.03287448,  3.96712552,  1.47897423]])

In [305]:
basic_baseline(A, 'PCC', 2)

array([[-0.01190878,  3.28877715,  1.98809122,  0.68740529,  2.05567246,
         1.98809122,  4.52188184,  0.68740529,  3.28877715,  3.22119591],
       [ 4.28571429,  1.28571429,  1.28571429,  4.28571429,  2.28571429,
         3.28571429,  5.28571429,  0.28571429,  4.28571429,  0.28571429],
       [ 0.76388889,  1.76388889,  2.76388889,  3.76388889, -0.23611111,
         2.76388889,  3.76388889,  3.76388889,  1.76388889,  4.76388889],
       [ 0.51388889,  1.51388889,  2.51388889,  3.51388889, -0.48611111,
         2.51388889,  3.51388889,  3.51388889,  1.51388889,  4.51388889],
       [ 3.23998233,  2.23113383,  0.9036995 ,  3.23998233,  2.89927525,
         3.89927525,  3.57626516,  1.23113383,  3.23998233,  0.89927525]])

In [299]:
A

array([[4, 1, 1, 4, 2, 3, 5, 0, 4, 0],
       [0, 4, 2, 0, 3, 2, 5, 0, 4, 3],
       [2, 0, 4, 5, 2, 0, 1, 3, 4, 2],
       [1, 4, 0, 1, 4, 5, 0, 3, 1, 2],
       [1, 2, 3, 4, 0, 3, 4, 4, 2, 5]])

In [300]:
basic_baseline(A, 'COS', 2)

[[1 4 2 3 0]
 [0 4 3 2 1]
 [4 1 0 3 2]
 [1 4 2 0 3]
 [1 0 2 3 4]]
[[1 4]
 [0 4]
 [4 1]
 [1 4]
 [1 0]]
5
10
3.0607142857142855
* 2.886111111111111


array([[ 0.28988047,  2.81978035,  2.28988047,  1.75998059,  1.32974698,
         2.28988047,  4.30981372,  1.75998059,  2.81978035,  3.77991384],
       [ 2.74888141,  1.72480939,  2.21879139,  4.2308274 ,  1.24286341,
         3.2308274 ,  4.7368454 ,  2.20675538,  3.24286341,  2.70073737],
       [ 0.18909227,  2.65715391,  2.18909227,  1.72103063,  1.14650779,
         2.18909227,  4.16780003,  1.72103063,  2.65715391,  3.69973839],
       [-0.08579346,  2.44582768,  1.91420654,  1.3825854 ,  0.95636806,
         1.91420654,  3.9352873 ,  1.3825854 ,  2.44582768,  3.40366616],
       [ 1.95132724,  2.47897423,  1.47107509,  1.95132724,  2.47107509,
         2.46317595,  4.96712552, -0.03287448,  3.96712552,  1.47897423]])

In [221]:
A

array([[4, 1, 1, 4, 2, 3, 5, 0, 4, 0],
       [0, 4, 2, 0, 3, 2, 5, 0, 4, 3],
       [2, 0, 4, 5, 2, 0, 1, 3, 4, 2],
       [1, 4, 0, 1, 4, 5, 0, 3, 1, 2],
       [1, 2, 3, 4, 0, 3, 4, 4, 2, 5]])

In [113]:
basic_baseline(MovieLens_pivot, 'COS', 2)

array([[ 1.81655320e+00,  1.81655320e+00,  1.81655320e+00, ...,
        -6.80315149e-01, -6.80315149e-01,  1.31717953e+00],
       [ 3.42179744e+00,  3.92253386e+00,  3.42179744e+00, ...,
        -5.76729721e-01,  1.91958819e+00, -5.76729721e-01],
       [ 4.58647989e+00,  5.08648408e+00,  5.08648408e+00, ...,
         8.64840756e-02,  8.64840756e-02,  2.08650080e+00],
       ...,
       [ 3.98392408e+00,  4.48403460e+00,  3.48381356e+00, ...,
         1.48447670e+00, -5.15965395e-01,  1.48359251e+00],
       [ 3.93045873e+00,  4.43023094e+00,  4.43023094e+00, ...,
        -5.69769058e-01, -5.69769058e-01,  3.43023094e+00],
       [ 5.00296743e+00,  2.50221309e+00,  2.50372176e+00, ...,
         2.96742717e-03,  2.00236396e+00,  2.96742717e-03]])

In [ ]:
basic_baseline(MovieLens_pivot, 'PCC', 2)

In [214]:
-6.80315149e-01

-0.680315149

In [213]:
-5.69769058e-01

-0.569769058

In [170]:
basic_baseline(A, 'COS', 2)

array([[ 0.28988047,  2.81978035,  2.28988047,  1.75998059,  1.32974698,
         2.28988047,  4.30981372,  1.75998059,  2.81978035,  3.77991384],
       [ 2.74888141,  1.72480939,  2.21879139,  4.2308274 ,  1.24286341,
         3.2308274 ,  4.7368454 ,  2.20675538,  3.24286341,  2.70073737],
       [ 0.18909227,  2.65715391,  2.18909227,  1.72103063,  1.14650779,
         2.18909227,  4.16780003,  1.72103063,  2.65715391,  3.69973839],
       [-0.08579346,  2.44582768,  1.91420654,  1.3825854 ,  0.95636806,
         1.91420654,  3.9352873 ,  1.3825854 ,  2.44582768,  3.40366616],
       [ 1.95132724,  2.47897423,  1.47107509,  1.95132724,  2.47107509,
         2.46317595,  4.96712552, -0.03287448,  3.96712552,  1.47897423]])